### ISSUE TITLE
Define is not defined

### ISSUE THREAD

**Issue by finitud** [ecto/duino#29]
Following the instructions I just keep getting a "define not defined" message. Example:

```
$ node examples/led.js
/Users/ruben/projects/arduino/noduino/node_modules/duino/lib/board.js:1
(function (exports, require, module, __filename, __dirname) { define(function(
                                                          ^
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/ruben/projects/arduino/noduino/node_modules/duino/lib/board.js:1:63)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/ruben/projects/arduino/noduino/node_modules/duino/index.js:3:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

**Comment by rohanrehman** [comment]
I am getting same error, did you figure this out?

**Comment by tjanson** [comment]
Try

``` js
if (typeof define !== 'function') {
  var define = require('amdefine')(module);
}
```

… Oh, this is way old. Well, maybe someone still has this issue.

**Comment by john-ka-peter** [comment]
I ma having the same problem. please help

<a href="http://javascripttrainingcourses.com/JS/Node-JS-Training" title="Node.js Training in Chennai">Node.js Training in Chennai</a>
