### ISSUE TITLE
Error: Serialport not open

### ISSUE THREAD

**Issue by anno143** [ecto/duino#59]
I am running example sensor.js and getting following error:

`1458988219328 duino info attempting to find Arduino board
1458988219400 duino info set pin A0 mode to in
1458988219403 duino info serial not ready, buffering message: 00A0000
1458988219455 duino debug attempting to open serial conn.: ttyACM0
1458988219462 duino info found board at /dev/ttyACM0
1458988219464 duino info binding serial events
1458988219471 duino info analogRead from pin A0
1458988219472 duino write 04A0000

Error: Serialport not open.
    at SerialPortFactory.SerialPort.write (/home/pi/SmartHome/node_modules/duino/node_modules/serialport/serialport.js:288:17)
    at Board.write (/home/pi/SmartHome/node_modules/duino/lib/board.js:163:17)
    at Board.analogRead (/home/pi/SmartHome/node_modules/duino/lib/board.js:235:7)
    at null.<anonymous> (/home/pi/SmartHome/node_modules/duino/lib/sensor.js:17:16)
    at wrapper [as _onTimeout](timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)`

I will appreciate your help

**Comment by gr67santafe** [comment]
maybe the baud is not right! set it carefully :)
